version: "2"

services:
  code:
    image: ubuntu:16.04
    volumes:
      - .:/go/src/github.com/euclid1990/gstats
  app:
    build: .
    image: gstats:latest
    restart: on-failure
    volumes_from:
      - code
    working_dir: /go/src/github.com/euclid1990/gstats
    ports:
      - "3000:3000"
    environment:
      - GOBIN=/go/bin
    tty: true
